#!/bin/bash


sec_group() {
SG_ID=$(aws ec2 create-security-group --group-name my-sg --description "My security group" --vpc-id "${VPC_ID}" --output text)
    if [ -z "$SG_ID" ]; then
        echo "Error creating Security Group!"
        exit 1
        else
                echo "Security group created!!"
    fi
    aws ec2 create-tags --resources "$SG_ID" --tags Key=Name,Value=MySG

aws ec2 authorize-security-group-ingress --group-id "${SG_ID}" --protocol tcp --port 22 --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-id "${SG_ID}" --protocol tcp --port 80 --cidr 0.0.0.0/0
echo "Rules created"
}

create_ec2() {
        local KEY="$1"
        local SUBNET_ID="$2"
        local SG_ID="$3"
        INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0557a15b87f6559cf --instance-type t2.micro --key-name "${KEY}" --security-group-ids "${SG_ID}" --subnet-id "${SUBNET_ID}" --query 'Instances[0].InstanceId' --output text)
        if [ -z "$INSTANCE_ID" ]; then
        echo "Error create EC2!"
        else
                echo "Instnace created!"
    fi
    aws ec2 create-tags --resources "$INSTANCE_ID" --tags Key=Name,Value=EC2
}

