#!/bin/bash

create_vpc() {
    VPC_ID=$(aws ec2 create-vpc --cidr-block 10.0.0.0/16 --query Vpc.VpcId --output text)
    if [ -z "$VPC_ID" ]; then
        echo "Error creating VPC!"
        exit 1
    fi
    aws ec2 create-tags --resources "$VPC_ID" --tags Key=Name,Value=MyVPC
    echo "$VPC_ID"
}

create_subnet() {
    local VPC_ID="$1"
    local CIDR="$2"
    local AZ="$3"
    SUBNET_ID=$(aws ec2 create-subnet --vpc-id "${VPC_ID}" --cidr-block "${CIDR}" --availability-zone "${AZ}" --query Subnet.SubnetId --output text)
    if [ -z "$SUBNET_ID" ]; then
        echo "Error creating subnet!"
        exit 1
    fi
    aws ec2 create-tags --resources "$SUBNET_ID" --tags Key=Name,Value=MySubnet
    echo $SUBNET_ID
}

public_ip() {
aws ec2 modify-subnet-attribute --subnet-id "${SUBNET_ID3}" --map-public-ip-on-launch
if [ "$?" -ne 0 ]; then
        echo "Error enabling auto-assign public IP addresses!"
        exit 1
        else
                echo "Auto-assign public IP addresses enabled for subnet ${SUBNET_ID3}!"
    fi
}
create_igw() {
    IGW_ID=$(aws ec2 create-internet-gateway --query InternetGateway.InternetGatewayId --output text)
    if [ -z "$IGW_ID" ]; then
        echo "Error creating Internet Gateway!"
        exit 1
    fi
    aws ec2 create-tags --resources "$IGW_ID" --tags Key=Name,Value=MyIGW
    echo $IGW_ID
}

attach_igw() {
    local VPC_ID="$1"
    local IGW_ID="$2"
    aws ec2 attach-internet-gateway --vpc-id "${VPC_ID}" --internet-gateway-id "${IGW_ID}"
    if [ "$?" -ne 0 ]; then
        echo "Error attaching Internet Gateway to VPC!"
        exit 1
        else
                echo "IGW attached to VPC!!"
        fi
}

create_route_table() {
    local VPC_ID="$1"
    RTB_ID=$(aws ec2 create-route-table --vpc-id "${VPC_ID}" --query RouteTable.RouteTableId --output text)
        if [ -z "$RTB_ID" ]; then
        echo "Error creating Route Table!"
        exit 1
    fi
    aws ec2 create-tags --resources "$RTB_ID" --tags Key=Name,Value=MyRTB
    echo $RTB_ID
}
create_route() {
    local RTB_ID="$1"
    local IGW_ID="$2"
    aws ec2 create-route --route-table-id "${RTB_ID}" --destination-cidr-block 0.0.0.0/0 --gateway-id "${IGW_ID}"
    if [ "$?" -ne 0 ]; then
        echo "Error creating route in the Route Table!"
        exit 1
        else
                echo "Some route in the RTB created!"
    fi
}

associate_route_table() {
    local RTB_ID="$1"
    local SUBNET_ID="$2"
    aws ec2 associate-route-table --route-table-id "${RTB_ID}" --subnet-id "${SUBNET_ID}"
    if [ "$?" -ne 0 ]; then
        echo "Error Associate!"
        exit 1
        else
                echo "Associated the route table with the public subnet!!"
    fi
}


