#!/bin/bash

INSTANCE_ID=$(aws ec2 describe-instances --query "sort_by(Reservations[].Instances[], &LaunchTime)[-1].InstanceId" --output text)

aws ec2 terminate-instances --instance-ids "${INSTANCE_ID}"
echo "Instance ${INSTANCE_ID} terminated"
aws ec2 wait instance-terminated --instance-ids "${INSTANCE_ID}"
echo "Instance ${INSTANCE_ID} terminated successfully"

aws ec2 delete-subnet --subnet-id "${SUBNET_ID0}"
echo "Subnet ${SUBNET_ID0} deleted "

aws ec2 delete-subnet --subnet-id "${SUBNET_ID1}"
echo "Subnet ${SUBNET_ID1} deleted "

aws ec2 delete-subnet --subnet-id "${SUBNET_ID2}"
echo "Subnet ${SUBNET_ID2} deleted "

aws ec2 delete-subnet --subnet-id "${SUBNET_ID3}"
echo "Subnet ${SUBNET_ID3} deleted "

aws ec2 delete-route-table --route-table-id "${RTB_ID}"
echo "Route table ${RTB_ID} deleted "

aws ec2 detach-internet-gateway --internet-gateway-id "${IGW_ID}" --vpc-id "${VPC_ID}"
echo "Internet gateway ${IGW_ID} detached from VPC ${VPC_ID}"

aws ec2 delete-internet-gateway --internet-gateway-id "${IGW_ID}"
echo "Internet gateway ${IGW_ID} deleted "

aws ec2 delete-key-pair --key-name my-key-pair
echo "Key pair ${KEY_PAIR} deleted"

aws ec2 delete-security-group --group-id "${SG_ID}"
echo "Security Group "${SG_ID}" deleted"

aws ec2 delete-vpc --vpc-id "${VPC_ID}"
echo "VPC ${VPC_ID} deleted"
